# Generated by Django 6.0.5 on 2026-05-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OmniScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('WEBSITE', 'Website / Web Application'), ('SYSTEM', 'System Network or Source Code'), ('HARDWARE', 'Hardware Firmware Binaries')], max_length=20)),
                ('target_identifier', models.CharField(help_text='URL, IP Address, Directory Path, or Firmware File Path', max_length=512)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assessment'), ('SCANNING', 'Running System Probes'), ('ANALYZING', 'AI Evaluation & Planning'), ('FIXING', 'Applying Patches'), ('COMPLETED', 'System Secured'), ('FAILED', 'Scan / Fix Failed')], default='PENDING', max_length=15)),
                ('raw_probe_output', models.TextField(blank=True, help_text='Raw outputs from Nmap/ZAP/Binwalk', null=True)),
                ('vulnerabilities_found', models.TextField(blank=True, help_text='AI-listed security gaps', null=True)),
                ('remediation_plan', models.TextField(blank=True, help_text='Step-by-step fix strategy created by AI', null=True)),
                ('execution_script', models.TextField(blank=True, help_text='AI-generated bash/python script to deploy the fix', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
