"""
Django settings for ByteGuard_Project project.

Generated by 'django-admin startproject' using Django 6.0.5.

Production Hardening & WhiteNoise Integration Configuration.
"""

import os
from pathlib import Path

# ─── 1. BASE DIRECTORY SETTINGS ──────────────────────────────────────────────
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ─── 2. SECURITY CONFIGURATIONS ──────────────────────────────────────────────
# SECURITY WARNING: keep the secret key used in production secret!
# Uses environment variable if present; falls back to development key locally.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY', 
    'django-insecure-b8)tk(^=3k^miz$e_y+(g+ra2cr#fd=&sycs^bjfte4@$d(5%a'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Automatically resolves to False on Render if DJANGO_DEBUG is set to 'False' or missing.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Explicitly mapping hosts allowed to bind to this service application
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.render.com',  # Automatically allows all Render subdomains
]


# ─── 3. CORE APPLICATION DEFINITIONS ─────────────────────────────────────────
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # WhiteNoise must run here to intercept static queries before standard apps
    'whitenoise.runserver_nostatic', 
    'django.contrib.staticfiles',
    'ByteGuard_ai',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CRITICAL: WhiteNoiseMiddleware must sit directly beneath SecurityMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ByteGuard_Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ByteGuard_Project.wsgi.application'


# ─── 4. DATABASE LAYER ───────────────────────────────────────────────────────
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ─── 5. IDENTITY & CREDENTIAL VALIDATION ─────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ─── 6. REGIONAL & LOCALE METRICS ────────────────────────────────────────────
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ─── 7. WHITENOISE PRODUCTION STATIC ASSET STORAGE PIPELINES ─────────────────
# URL path prefix to target served assets
STATIC_URL = '/static/'

# The absolute directory folder destination where `collectstatic` compiles assets
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Production directory hooks scanning for localized asset components
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Advanced compression engine configurations for handling manifest asset logs
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# ─── 8. INTERFACE PRIMITIVES ─────────────────────────────────────────────────
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
